baseURL = "https://threatprophet.com/"
languageCode = "en-us"
title = "ThreatProphet"
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  defaultTheme = "dark"
  author = "ThreatProphet"
  description = "Threat Intelligence & Adversary Research"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  hideFooter = true

[params.homeInfoParams]
  Title = "ThreatProphet"
  Content = "Independent threat intelligence research. Tracking adversaries, analyzing malware, and documenting campaigns."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/threatprophet"

[[params.socialIcons]]
  name = "twitter"
  url = "https://x.com/threatprophet"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
